
.. |SHIELD:svg:gh:hdl:constraints| image:: https://img.shields.io/badge/hdl-constraints-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/constraints on github
   :height: 22
   :target: https://github.com/hdl/constraints
.. |SHIELD:png:gh:hdl:constraints| image:: https://raster.shields.io/badge/hdl-constraints-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/constraints on github
   :height: 22
   :target: https://github.com/hdl/constraints


.. |SHIELD:svg:gh:hdl:packages| image:: https://img.shields.io/badge/hdl-packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/packages on github
   :height: 22
   :target: https://github.com/hdl/packages
.. |SHIELD:png:gh:hdl:packages| image:: https://raster.shields.io/badge/hdl-packages-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/packages on github
   :height: 22
   :target: https://github.com/hdl/packages


.. |SHIELD:svg:gh:hdl:awesome| image:: https://img.shields.io/badge/hdl-awesome-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/awesome on github
   :height: 22
   :target: https://github.com/hdl/awesome
.. |SHIELD:png:gh:hdl:awesome| image:: https://raster.shields.io/badge/hdl-awesome-f2f1ef.svg?longCache=true&style=flat-square&logo=GitHub&logoColor=f2f1ef
   :alt: hdl/awesome on github
   :height: 22
   :target: https://github.com/hdl/awesome


.. |SHIELD:svg:Reports-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:Reports-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
